### ISSUE TITLE
created src file name does not satisfy jquery plugin convention 

### ISSUE THREAD

**Issue by christian-meyer-jimdo** [Jimdo/generator-jquery-plugin#2]
I created a plugin with name "jquery-jd-scrollpane".
The file was created with "jqueryJdScrollpane.js"
I would rather expect: "jquery.jdScrollpane" or "jquery.plugin.jdScrollpane"

**Comment by Xiphe** [comment]
same as #3 i think more magic than camelCase conversion would be overengineered
